import java.lang.annotation.Repeatable;

/**
 * If the annotations have the same type, then this is called a repeating annotation:
 * We can use repeat annotation anywhere that we would use a standard annotation
 * Ex: Class, variables, fields
 * repeating annotations are stored in a container annotation that is automatically generated by the Java compiler
 */

public class RepeatingAnnotations {

    @Schedule(dayOfMonth = "last")
    @Schedule(dayOfWeek = "Fri", hour = 23)
    public void doPeriodicCleanUp() {}

//     Declaring a repeatable annotation
    @Repeatable(Schedules.class)
    public @interface Schedule {
        String dayOfMonth() default "first";
        String dayOfWeek() default "Mon";
        int hour () default 12;
    }

//    The containing annotation type
    public @interface Schedules {
        Schedule[] value();
    }

}


